services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=product'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '4002:3306'
