# Eureka server configuration
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://mirzaazwad:123@cluster0.1nfyxcz.mongodb.net/product?retryWrites=true&w=majority


server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      hostname: localhost
